Repository ucsb-cs156-w24/proj-happy-cows-w24-4pm-4, pull requests merged in 2024-03, with the labels that each got.

#33 AN - added entity/repository for announcements
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcements.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementsRepository.java
Labels: 5

#34 RM - added showChat checkbox to frontend and tests
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
Labels: 10

#35 Kole - Announcements F1
  frontend/src/fixtures/announcementsFixtures.js
  frontend/src/main/components/Announcements/AnnouncementsForm.js
  frontend/src/main/components/Announcements/AnnouncementsTable.js
  frontend/src/main/utils/announcementsUtils.js
  frontend/src/stories/components/Announcements/AnnouncementsForm.stories.js
  frontend/src/stories/components/Announcements/AnnouncementsTable.stories.js
  frontend/src/tests/components/Announcements/announcementsForm.test.js
  frontend/src/tests/components/Announcements/announcementsTable.test.js
  frontend/src/tests/utils/announcementsUtils.test.js
Labels: enhancement, 10

#38 AN - B2 added controllers and tests for Announcements
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 20

#43 Merging CHAT-ON-OFF epic issue into main
  docs/proj-happy-cows-w24-4pm-4 - Shortcut.lnk
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/PlayPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/UserCommonsTests.java
Labels: 40
